(()=>{
'use strict';window.__qfEditing=true;
let selected=null,patches=[],history=[],input=null,browsing=false,drag=null;
const send=data=>parent.postMessage({channel:'qinfang-direct-edit',...data},'*'),copy=x=>JSON.parse(JSON.stringify(x));
const ui=document.createElement('div');ui.id='qf-edit-ui';ui.style.cssText='position:fixed;inset:0;pointer-events:none;z-index:2147483646';document.body.append(ui);
const style=document.createElement('style');style.textContent='[data-edit-selected]{outline:2px solid #d89244!important;outline-offset:3px!important}#qf-edit-input{position:fixed;z-index:2147483647;box-sizing:border-box;background:#fffdf7;color:#26343d;border:2px solid #d89244;border-radius:6px;padding:6px;resize:both;min-height:44px}#qf-edit-ui button{position:absolute;width:14px;height:14px;padding:0;background:white;border:2px solid #d89244;border-radius:50%;pointer-events:auto;cursor:move}';document.head.append(style);
function rawSelector(el){let parts=[];while(el&&el!==document.documentElement){if(/^[A-Za-z_][\w-]*$/.test(el.id)){parts.unshift('#'+el.id);return parts.join(' > ')}const tag=el.tagName.toLowerCase(),siblings=[...el.parentElement.children].filter(x=>x.tagName===el.tagName);parts.unshift(tag+':nth-of-type('+(siblings.indexOf(el)+1)+')');el=el.parentElement}return 'html > '+parts.join(' > ')}
function selector(el){const base=rawSelector(el),owner=el.closest('[data-phase]');return owner&&owner!==el&&/^[a-zA-Z0-9_-]+$/.test(owner.dataset.phase)?rawSelector(owner)+'[data-phase="'+owner.dataset.phase+'"] '+base:base}
function object(){return selected?.id.startsWith('qf-object-')?patches.find(p=>p.kind==='object'&&p.selector==='#'+selected.id)||JSON.parse(selected.dataset.qfSignature):null}
function isLine(){return selected&&(object()?.shape==='line'||['line','polyline','path'].includes(selected.localName))}
function record(){const el=selected,path=el?selector(el):null,clone=el?.cloneNode(true),prior=copy(patches),ids=new Set([...document.querySelectorAll('[id^="qf-object-"]')].map(x=>x.id));history.push(()=>{for(const n of document.querySelectorAll('[id^="qf-object-"]'))if(!ids.has(n.id))n.remove();document.querySelectorAll('[data-edit-selected]').forEach(n=>n.removeAttribute('data-edit-selected'));if(el&&clone){(document.querySelector(path)||el).replaceWith(clone);selected=clone}else selected=null;patches=prior})}
function put(p){let old=patches.find(x=>x.kind===p.kind&&x.selector===p.selector);if(old){if(p.kind==='text')old.after=p.after;else if(p.values)Object.assign(old.values,p.values);else Object.assign(old,p)}else patches.push(p);window.QfEditApply(p)}
function notice(){send({type:'selection',text:selected?.textContent||'',selected:!!selected,line:!!isLine(),count:patches.length,canUndo:history.length>0});handles()}
function commit(){if(!input)return;const value=input.value;input.remove();input=null;if(!selected)return;const obj=object();if(obj?.shape==='box'){if(obj.text!==value){record();put({...obj,text:value})}}else if(value!==selected.textContent){record();put({kind:'text',selector:selector(selected),before:selected.textContent,after:value})}notice()}
function select(el){commit();selected?.removeAttribute('data-edit-selected');selected=el;selected?.setAttribute('data-edit-selected','');notice()}
function edit(){if(!selected||input||isLine())return;const obj=object();if(!obj&&selected.children.length&&!['text','tspan','h1','h2','h3','p','span','li','td'].includes(selected.localName)){send({type:'hint',text:'双击框内文字修改；删除整组请用“删除对象”'});return}const r=selected.getBoundingClientRect();input=document.createElement('textarea');input.id='qf-edit-input';input.setAttribute('aria-label','修改对象文字');input.value=obj?.text??selected.textContent;Object.assign(input.style,{left:Math.max(8,Math.min(r.left,innerWidth-300))+'px',top:Math.max(8,Math.min(r.top,innerHeight-120))+'px',width:Math.min(innerWidth-16,Math.max(280,r.width))+'px',height:'100px',font:'18px Microsoft YaHei'});document.body.append(input);input.focus();input.select();input.oninput=()=>send({type:'dirty'});input.onblur=commit;input.onkeydown=e=>{e.stopPropagation();if(e.key==='Escape'){input.remove();input=null}else if(e.key==='Enter'&&(e.metaKey||e.ctrlKey)){e.preventDefault();commit()}}}
function local(x,y,el=selected){const m=el instanceof SVGElement?el.getScreenCTM():null;return m?new DOMPoint(x,y).matrixTransform(m.inverse()):{x,y}}
function endpoints(){const obj=object();if(obj)return[{x:obj.x,y:obj.y},{x:obj.x2,y:obj.y2}];try{if(selected.localName==='line')return[{x:+selected.getAttribute('x1'),y:+selected.getAttribute('y1')},{x:+selected.getAttribute('x2'),y:+selected.getAttribute('y2')}];return[selected.getPointAtLength(0),selected.getPointAtLength(selected.getTotalLength())]}catch{return null}}
function lineUpdate(pts,route='straight'){const [a,b]=pts,obj=object();if(obj){put({...obj,x:a.x,y:a.y,x2:b.x,y2:b.y,route});return}const list=route==='straight'?[a,b]:route==='vertical'?[a,{x:a.x,y:b.y},b]:[a,{x:b.x,y:a.y},b];let values;if(selected.localName==='line'){values={x1:''+a.x,y1:''+a.y,x2:''+b.x,y2:''+b.y};if(route!=='straight'){const m=selected.getScreenCTM(),a2=new DOMPoint(a.x,a.y).matrixTransform(m),b2=new DOMPoint(b.x,b.y).matrixTransform(m);put({kind:'hide',selector:selector(selected)});selected.removeAttribute('data-edit-selected');const o={kind:'object',selector:'#qf-object-'+crypto.randomUUID(),shape:'line',x:a2.x,y:a2.y,x2:b2.x,y2:b2.y,route};put(o);selected=document.querySelector(o.selector);selected.setAttribute('data-edit-selected','');return}}else if(selected.localName==='polyline')values={points:list.map(p=>`${p.x},${p.y}`).join(' ')};else values={d:list.map((p,i)=>`${i?'L':'M'} ${p.x} ${p.y}`).join(' ')};put({kind:'attrs',selector:selector(selected),values})}
function handles(){ui.replaceChildren();if(!selected||browsing)return;const r=selected.getBoundingClientRect();const add=(x,y,kind,label)=>{const b=document.createElement('button');b.title=label;b.setAttribute('aria-label',label);b.style.left=x-7+'px';b.style.top=y-7+'px';b.onpointerdown=e=>start(e,kind);ui.append(b)};if(isLine()){const pts=endpoints();if(pts)pts.forEach((p,i)=>{const m=selected.getScreenCTM(),q=m?new DOMPoint(p.x,p.y).matrixTransform(m):p;add(q.x,q.y,'end'+i,i?'拖动终点':'拖动起点')})}else add(r.right,r.bottom,'resize','拖动调整大小')}
function start(e,kind){if(!selected)return;e.preventDefault();e.stopImmediatePropagation();commit();record();drag={kind,x:e.clientX,y:e.clientY,el:selected,obj:object()?copy(object()):null,rect:selected.getBoundingClientRect(),width:selected.offsetWidth,inverse:selected instanceof SVGElement?selected.getScreenCTM().inverse():null,transform:selected.getAttribute('transform')||'',translate:getComputedStyle(selected).translate,pts:isLine()?endpoints():null};drag.local=local(e.clientX,e.clientY);ui.style.pointerEvents='auto'}
document.addEventListener('pointermove',e=>{if(!drag)return;e.preventDefault();const d=drag,dx=e.clientX-d.x,dy=e.clientY-d.y,p=d.inverse?new DOMPoint(e.clientX,e.clientY).matrixTransform(d.inverse):{x:e.clientX,y:e.clientY},lx=p.x-d.local.x,ly=p.y-d.local.y;if(d.kind.startsWith('end')){const pts=d.pts.map(p=>({x:p.x,y:p.y}));pts[+d.kind.slice(-1)]={x:p.x,y:p.y};lineUpdate(pts,d.obj?.route||'straight')}else if(d.obj){let o={...d.obj};if(d.kind==='resize'){o.w=Math.max(40,o.w+dx);o.h=Math.max(40,o.h+dy)}else{o.x+=dx;o.y+=dy;if(o.shape==='line'){o.x2+=dx;o.y2+=dy}}put(o)}else if(d.kind==='resize'){if(d.el instanceof SVGElement){const box=d.el.getBBox(),sx=Math.max(.1,(d.rect.width+dx)/d.rect.width),sy=Math.max(.1,(d.rect.height+dy)/d.rect.height);put({kind:'attrs',selector:selector(d.el),values:{transform:`${d.transform} translate(${box.x} ${box.y}) scale(${sx} ${sy}) translate(${-box.x} ${-box.y})`}})}else put({kind:'style',selector:selector(d.el),values:{width:Math.max(30,d.width+dx)+'px',height:Math.max(25,d.rect.height+dy)+'px'}})}else if(d.el instanceof SVGElement){put({kind:'attrs',selector:selector(d.el),values:{transform:`${d.transform} translate(${lx} ${ly})`}})}else{const base=d.translate==='none'?[0,0]:d.translate.split(' ').map(parseFloat);put({kind:'style',selector:selector(d.el),values:{translate:`${(base[0]||0)+dx}px ${(base[1]||0)+dy}px`}})}handles()},true);
document.addEventListener('pointerup',()=>{if(drag){drag=null;ui.style.pointerEvents='none';notice()}},true);
document.addEventListener('pointerdown',e=>{if(browsing||e.target===input||ui.contains(e.target))return;const el=e.target.closest('[id^="qf-object-"]')||e.target.closest('text,tspan,rect,path,line,polyline,polygon,circle,ellipse,g,h1,h2,h3,p,li,td,th,span,strong,div');if(!el||el===document.body||el===ui||el.id==='qf-drawing-layer')return;select(el);start(e,'move')},true);
document.addEventListener('click',e=>{if(!browsing&&e.target!==input){e.preventDefault();e.stopImmediatePropagation()}},true);
document.addEventListener('dblclick',e=>{if(!browsing&&e.target!==input){e.preventDefault();e.stopImmediatePropagation();edit()}},true);
function add(shape){commit();selected?.removeAttribute('data-edit-selected');selected=null;record();const p={kind:'object',selector:'#qf-object-'+crypto.randomUUID(),shape,x:420,y:280,...(shape==='box'?{w:240,h:110,text:'双击修改文字'}:{x2:700,y2:400,route:'horizontal'})};put(p);select(document.querySelector(p.selector))}
window.addEventListener('message',e=>{if(e.source!==parent||e.data?.channel!=='qinfang-direct-edit')return;const c=e.data.command;commit();if(c==='browse'){browsing=!browsing;selected?.removeAttribute('data-edit-selected');handles();return}if(c==='box'||c==='line'){add(c);return}if(c==='edit')edit();if(c==='parent'&&selected){const parent=selected.parentElement;if(parent&&parent!==document.body&&parent!==document.documentElement&&parent.localName!=='svg')select(parent);else send({type:'hint',text:'已到画布边界，不能选中整页'})}if(c==='delete'&&selected){record();put({kind:'hide',selector:selector(selected)});selected.removeAttribute('data-edit-selected');selected=null;notice()}if(c==='undo'&&history.length){history.pop()();notice()}if(c.startsWith('route-')&&isLine()){record();lineUpdate(endpoints(),c.slice(6));notice()}if(c==='export')send({type:'export',patches})});
send({type:'ready'});
})();
